"""Permanent stream layout for the native PersonaPlex-Agent fork.

PersonaPlex has one text lane plus two eight-codebook audio lanes.  This module
defines the two additional *typed* lanes required by the agentic model:

* ``model_action``: generated by the model;
* ``environment_result``: supplied only by the executor/runtime.

They must not be represented as extra Mimi audio codebooks because their
vocabulary, loss, causality, and provenance are different.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .protocol import ObservationKind


BASE_FRAME_MS = 80
ACTION_PACKET_FRAMES = 2
ACTION_PACKET_MS = BASE_FRAME_MS * ACTION_PACKET_FRAMES
MAX_ACTION_TOKENS_PER_PACKET = 10
MAX_ACTION_TOKENS_PER_FRAME = MAX_ACTION_TOKENS_PER_PACKET // ACTION_PACKET_FRAMES
AUDIO_CODEBOOKS_PER_SPEAKER = 8


class NativeStream(str, Enum):
    ASSISTANT_TEXT = "assistant_text"
    ASSISTANT_AUDIO = "assistant_audio"
    USER_AUDIO = "user_audio"
    MODEL_ACTION = "model_action"
    ENVIRONMENT_RESULT = "environment_result"


@dataclass(frozen=True, slots=True)
class AgentStreamLayout:
    """Stable slot map for the forked temporal transformer input cache."""

    assistant_text_slot: int = 0
    assistant_audio_start: int = 1
    user_audio_start: int = 9
    model_action_slot: int = 17
    environment_result_slot: int = 18

    @property
    def total_streams(self) -> int:
        return self.environment_result_slot + 1

    @property
    def assistant_audio_slots(self) -> range:
        return range(self.assistant_audio_start, self.assistant_audio_start + AUDIO_CODEBOOKS_PER_SPEAKER)

    @property
    def user_audio_slots(self) -> range:
        return range(self.user_audio_start, self.user_audio_start + AUDIO_CODEBOOKS_PER_SPEAKER)

    def validate(self) -> None:
        if len(self.assistant_audio_slots) != AUDIO_CODEBOOKS_PER_SPEAKER:
            raise ValueError("assistant audio must occupy eight Mimi codebooks")
        if len(self.user_audio_slots) != AUDIO_CODEBOOKS_PER_SPEAKER:
            raise ValueError("user audio must occupy eight Mimi codebooks")
        if self.model_action_slot in set(self.assistant_audio_slots) | set(self.user_audio_slots):
            raise ValueError("model_action cannot share an audio slot")
        if self.environment_result_slot in set(self.assistant_audio_slots) | set(self.user_audio_slots):
            raise ValueError("environment_result cannot share an audio slot")
        if self.model_action_slot == self.environment_result_slot:
            raise ValueError("action and environment result need distinct streams")


@dataclass(frozen=True, slots=True)
class ActionPacket:
    """Bounded model-generated action tokens for one 160 ms logical packet."""

    start_frame: int
    call_id: str | None
    tokens: tuple[str, ...]

    def __post_init__(self) -> None:
        if self.start_frame < 0 or self.start_frame % ACTION_PACKET_FRAMES:
            raise ValueError("action packets must begin on an even, non-negative 80 ms frame")
        if not self.tokens:
            raise ValueError("action packets must contain at least one token")
        if len(self.tokens) > MAX_ACTION_TOKENS_PER_PACKET:
            raise ValueError("action packet exceeds the per-160-ms token budget")

    def tokens_for_frame(self, frame: int) -> tuple[str, ...]:
        """Split an action burst across the two 80 ms frames in its packet."""

        if frame not in (self.start_frame, self.start_frame + 1):
            raise ValueError("frame is outside this action packet")
        boundary = MAX_ACTION_TOKENS_PER_FRAME
        return self.tokens[:boundary] if frame == self.start_frame else self.tokens[boundary:]


@dataclass(frozen=True, slots=True)
class EnvironmentPacket:
    """Input-only executor observation, injected on a future causal frame."""

    frame: int
    call_id: str
    tokens: tuple[str, ...]
    kind: ObservationKind = ObservationKind.RESULT
    source: str = "tool_executor"

    def __post_init__(self) -> None:
        if self.frame < 0:
            raise ValueError("environment frame must be non-negative")
        if not self.call_id:
            raise ValueError("environment packets require a call ID")
        if not self.tokens:
            raise ValueError("environment packets must contain at least one token")
        if self.source != "tool_executor":
            raise ValueError("only tool_executor may author result observations")
